# Generated by Django 5.0.1 on 2026-03-02 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('1.1', 'Part 1.1 - Informal Letter (50+ words)'), ('1.2', 'Part 1.2 - Formal Letter (120+ words)'), ('2', 'Part 2 - Essay (180+ words)')], max_length=3)),
                ('question_text', models.TextField()),
                ('level', models.CharField(choices=[('A1', 'A1 (Beginner)'), ('A2', 'A2 (Elementary)'), ('B1', 'B1 (Intermediate)'), ('B2', 'B2 (Upper Intermediate)'), ('C1', 'C1 (Advanced)'), ('C2', 'C2 (Proficient)')], default='B1', max_length=2)),
                ('sample_answer', models.TextField(blank=True, help_text='Model answer for reference')),
                ('min_word_count', models.PositiveIntegerField(default=50)),
                ('max_word_count', models.PositiveIntegerField(default=250)),
                ('time_limit_minutes', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['task_type', 'level'],
            },
        ),
        migrations.CreateModel(
            name='WritingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('word_count', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('task_response_score', models.FloatField(blank=True, help_text='How well the task was addressed (0-5)', null=True)),
                ('coherence_score', models.FloatField(blank=True, help_text='Organization and linking (0-5)', null=True)),
                ('vocabulary_score', models.FloatField(blank=True, help_text='Range and accuracy of vocabulary (0-5)', null=True)),
                ('grammar_score', models.FloatField(blank=True, help_text='Range and accuracy of grammar (0-5)', null=True)),
                ('overall_score', models.FloatField(blank=True, help_text='Overall writing score (0-5)', null=True)),
                ('estimated_band', models.CharField(blank=True, choices=[('A1', 'A1 (Beginner)'), ('A2', 'A2 (Elementary)'), ('B1', 'B1 (Intermediate)'), ('B2', 'B2 (Upper Intermediate)'), ('C1', 'C1 (Advanced)'), ('C2', 'C2 (Proficient)')], max_length=2, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True, help_text='What was done well')),
                ('weaknesses', models.TextField(blank=True, help_text='Areas for improvement')),
                ('grammar_mistakes', models.TextField(blank=True, help_text='List of grammar mistakes')),
                ('vocabulary_suggestions', models.TextField(blank=True, help_text='Better vocabulary alternatives')),
                ('improved_version', models.TextField(blank=True, help_text='AI-improved version')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_attempts', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.writingquestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('total_time_minutes', models.PositiveIntegerField(default=0)),
                ('total_words_written', models.PositiveIntegerField(default=0)),
                ('letter_avg', models.FloatField(default=0.0)),
                ('essay_avg', models.FloatField(default=0.0)),
                ('vocabulary_improvement', models.FloatField(default=0.0)),
                ('grammar_improvement', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
