# Generated by Django 5.0.1 on 2026-03-02 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('1', 'Part 1 - Introduction'), ('1.2', 'Part 1.2 - Picture Description'), ('2', 'Part 2 - Situation'), ('3', 'Part 3 - Topic Discussion')], max_length=3)),
                ('question_text', models.TextField()),
                ('level', models.CharField(choices=[('A1', 'A1 (Beginner)'), ('A2', 'A2 (Elementary)'), ('B1', 'B1 (Intermediate)'), ('B2', 'B2 (Upper Intermediate)'), ('C1', 'C1 (Advanced)'), ('C2', 'C2 (Proficient)')], default='B1', max_length=2)),
                ('picture1_url', models.URLField(blank=True, null=True)),
                ('picture2_url', models.URLField(blank=True, null=True)),
                ('pros', models.TextField(blank=True, help_text='Pros for topic discussion', null=True)),
                ('cons', models.TextField(blank=True, help_text='Cons for topic discussion', null=True)),
                ('time_limit', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['part', 'level'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='speaking/audio/')),
                ('transcribed_text', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('fluency_score', models.FloatField(blank=True, help_text='0-5 scale', null=True)),
                ('grammar_score', models.FloatField(blank=True, help_text='0-5 scale', null=True)),
                ('vocabulary_score', models.FloatField(blank=True, help_text='0-5 scale', null=True)),
                ('pronunciation_score', models.FloatField(blank=True, help_text='0-5 scale', null=True)),
                ('overall_score', models.FloatField(blank=True, help_text='0-5 scale', null=True)),
                ('feedback', models.TextField(blank=True)),
                ('mistakes', models.TextField(blank=True, help_text='List of mistakes found')),
                ('improved_version', models.TextField(blank=True, help_text='AI-improved version')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_attempts', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speaking.speakingquestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('total_time_minutes', models.PositiveIntegerField(default=0)),
                ('part1_avg', models.FloatField(default=0.0)),
                ('part2_avg', models.FloatField(default=0.0)),
                ('part3_avg', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
