# Generated by Django 5.0.1 on 2026-03-02 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('total_speaking_attempts', models.PositiveIntegerField(default=0)),
                ('total_writing_attempts', models.PositiveIntegerField(default=0)),
                ('total_practice_time_minutes', models.PositiveIntegerField(default=0)),
                ('avg_speaking_score', models.FloatField(default=0.0)),
                ('avg_writing_score', models.FloatField(default=0.0)),
                ('avg_overall_score', models.FloatField(default=0.0)),
                ('total_messages_sent', models.PositiveIntegerField(default=0)),
                ('total_coins_earned', models.PositiveIntegerField(default=0)),
                ('total_xp_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('cpu_usage_avg', models.FloatField(default=0.0, help_text='Average CPU usage %')),
                ('memory_usage_avg', models.FloatField(default=0.0, help_text='Average memory usage %')),
                ('disk_usage', models.FloatField(default=0.0, help_text='Disk usage %')),
                ('response_time_avg', models.FloatField(default=0.0, help_text='Average bot response time in seconds')),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('openai_api_calls', models.PositiveIntegerField(default=0)),
                ('openai_tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CommonMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('speaking', 'Speaking'), ('writing', 'Writing')], max_length=8)),
                ('mistake_type', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('pronunciation', 'Pronunciation'), ('fluency', 'Fluency'), ('coherence', 'Coherence'), ('task_response', 'Task Response')], max_length=15)),
                ('mistake_text', models.CharField(max_length=255)),
                ('frequency', models.PositiveIntegerField(default=0, help_text='How many times this mistake was made')),
                ('suggestion', models.TextField(help_text='AI-generated suggestion to fix this mistake')),
                ('example_correction', models.TextField(help_text='Example of correct usage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_users', models.ManyToManyField(related_name='common_mistakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-frequency'],
                'unique_together': {('skill', 'mistake_type', 'mistake_text')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('current_level', models.CharField(max_length=2)),
                ('speaking_score', models.FloatField()),
                ('writing_score', models.FloatField()),
                ('overall_score', models.FloatField()),
                ('speaking_improvement', models.FloatField(default=0.0, help_text='Change from last period')),
                ('writing_improvement', models.FloatField(default=0.0, help_text='Change from last period')),
                ('overall_improvement', models.FloatField(default=0.0, help_text='Change from last period')),
                ('total_practice_time', models.PositiveIntegerField(default=0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('next_milestone', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('user', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', 'User Registration'), ('speaking_start', 'Speaking Practice Started'), ('speaking_complete', 'Speaking Practice Completed'), ('writing_start', 'Writing Practice Started'), ('writing_complete', 'Writing Practice Completed'), ('level_up', 'Level Up'), ('streak_achieved', 'Streak Achievement'), ('coins_earned', 'Coins Earned'), ('login', 'User Login')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='analytics_u_user_id_3bcd80_idx'), models.Index(fields=['action', 'created_at'], name='analytics_u_action_ca6447_idx')],
            },
        ),
    ]
